<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD9fsHiL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD9fsHiL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD9fsHiL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD9fsHiL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerD9fsHiL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'D9fsHiL',
    'container.build_id' => 'ea6e8431',
    'container.build_time' => 1646210874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD9fsHiL');
