<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'add_events' => [[], ['_controller' => 'App\\Controller\\EventController::addEvents'], [], [['text', '/add-events']], [], []],
    'events' => [[], ['_controller' => 'App\\Controller\\EventController::events'], [], [['text', '/events']], [], []],
    'events1' => [[], ['_controller' => 'App\\Controller\\EventController::events1'], [], [['text', '/events1']], [], []],
    'eventss' => [['id'], ['_controller' => 'App\\Controller\\EventController::eventss'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/eventss']], [], []],
    'modify_events' => [['id'], ['_controller' => 'App\\Controller\\EventController::modifyEvent'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modify-events']], [], []],
    'delete_events' => [['id'], ['_controller' => 'App\\Controller\\EventController::deleteEvent'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/delete-events']], [], []],
    'add_participation' => [[], ['_controller' => 'App\\Controller\\ParticipationController::addParticipation'], [], [['text', '/add-participation']], [], []],
    'participations' => [[], ['_controller' => 'App\\Controller\\ParticipationController::participations'], [], [['text', '/participations']], [], []],
    'modify_participation' => [['id'], ['_controller' => 'App\\Controller\\ParticipationController::modifyParticipation'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modify-participation']], [], []],
    'delete_participations' => [['id'], ['_controller' => 'App\\Controller\\ParticipationController::deleteParticipation'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/delete-participations']], [], []],
    'test1' => [[], ['_controller' => 'App\\Controller\\Test1Controller::index'], [], [['text', '/test1']], [], []],
];
